// Code generated by templ@(devel) DO NOT EDIT.

package card

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func cbd(payload , topic, me string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_cbd_c36d`,
		Function: `function __templ_cbd_c36d(payload, topic, me){// console.log(topic, {data: { id : payload }}, me);
  call(topic, {data: { id : payload }}, me);}`,
		Call: templ.SafeScript(`__templ_cbd_c36d`, payload, topic, me),
	}
}

func Badge() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		// Element (standard)
		_, err = templBuffer.WriteString("<a")
		if err != nil {
			return err
		}
		// Element Attributes
		_, err = templBuffer.WriteString(" href=\"#\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(" class=\"x-item\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(" data-id=\"\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(" data-target=\"html\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(" data-function=\"svc.post.edit\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(">")
		if err != nil {
			return err
		}
		// Text
		var_2 := `Edit`
		_, err = templBuffer.WriteString(var_2)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</a>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = io.Copy(w, templBuffer)
		}
		return err
	})
}

